### ISSUE TITLE
[Idea] Scrape Labeled Training Images From Google 

### ISSUE THREAD

**Issue by BritneyMuller** [MLTSEO/MLTS#2]
[Wrote this today](https://github.com/BritneyMuller/Google-DevTools-Snippets) to go with my talk, but would love to have it hosted here instead!

Let me know if/where you think this should live @jroakes :)

Thanks!!!

**Comment by jroakes** [comment]
Added:
https://github.com/MLTSEO/MLTS/tree/master/Tutorials/Training%20Data/Get%20Images%20in%20Chrome%20DevTools

JR
